apiVersion: v2
name: jcc
description: John Casablancas Centers applicant platform
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - jcc
  - nodejs
  - postgresql
maintainers:
  - name: JCC DevOps
