apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jcc.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "jcc.labels" . | nindent 4 }}
data:
  FRONTEND_URL: {{ .Values.configmap.frontendUrl | quote }}
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
